#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Jaret Lane
Exercise 7.20
January 21st 2022
"""

import numpy as np
import random


#Single element
print('Single element (list time first, array second): ')
%timeit rand_list=[random.randrange(1,7) for i in range(1)]
%timeit rand_array=np.random.randint(1,7,1)
print()

#10
print('10 elements (list time first, array second): ')
%timeit rand_list=[random.randrange(1,7) for i in range(10)]
%timeit rand_array=np.random.randint(1,7,10)
print()

#100
print('100 elements (list time first, array second): ')
%timeit rand_list=[random.randrange(1,7) for i in range(100)]
%timeit rand_array=np.random.randint(1,7,100)
print()

#1,000
print('1000 elements (list time first, array second): ')
%timeit rand_list=[random.randrange(1,7) for i in range(1000)]
%timeit rand_array=np.random.randint(1,7,1000)
print()

#10,000
print('10000 elements (list time first, array second): ')
%timeit rand_list=[random.randrange(1,7) for i in range(10000)]
%timeit rand_array=np.random.randint(1,7,10000)
print()

#100,000
print('100000 elements (list time first, array second): ')
%timeit rand_list=[random.randrange(1,7) for i in range(100000)]
%timeit rand_array=np.random.randint(1,7,100000)
print()

#1,000,000
print('1000000 elements (list time first, array second): ')
%timeit rand_list=[random.randrange(1,7) for i in range(1000000)]
%timeit rand_array=np.random.randint(1,7,1000000)
print()